POST http://localhost:3001/api/workouts
Content-Type: application/json

{
  "results": [
    {
    "name": "Military press",
    "type": "Barbell",
    "weight": 55,
    "repetitions": 4,
    "sets": 1
    },
        {
    "name": "Bench press",
    "type": "Dumbbell",
    "weight": 70,
    "repetitions": 3,
    "sets": 1
    }
  ]
}