POST http://localhost:3001/api/workouts
Content-Type: application/json

{
  "results": [
    {
    "name": "Military press",
    "type": "Barbell",
    "weight": 55,
    "repetitions": 4,
    "sets": 1
    }
  ]
}